### ISSUE TITLE
Copy files from android to usb drive root directory...

### ISSUE THREAD

**Issue by Shuhratjava** [mjdev/libaums#1]
Hi, thanks for sharing great job. Could you provide a way how to copy android files to usb drive? 
Thanks in advance.

**Comment by mjdev** [comment]
Hey,

thanks for your interest.
Do you mean in the example application or an example of how to do it in general?

**Comment by Shuhratjava** [comment]
Actually, I did it by using your create new file logic on options menu. Anyway thanks again, very good job.

**Comment by Shuhrat-java** [comment]
How to access usb drive and do several tasks at one time(Copying, file creation, video playing)? Is there some multithreading thing I should do?

**Comment by mjdev** [comment]
Hello,

you can use different threads and access the USB device as you like, I think (I never tried).
