### ISSUE TITLE
Capacity of USB drive.

### ISSUE THREAD

**Issue by Shuhrat-java** [mjdev/libaums#11]
Hello.
How can I know the capacity of USB drive? Seems there is not any API which gives that feature. I need to know how much free space left for writing

**Comment by mjdev** [comment]
Hey there,

you are right, this is currently not exposed by the API,but supported in some way in FAT32. I will take care of that. In the meantime you can easily add that feature yourself by delegating the required method calls down to the FAT32 layer or by nasty casting of the FSFileSystem things.

**Comment by Shuhrat-java** [comment]
Thanks. However I have no idea how to do that

**Comment by mjdev** [comment]
Hey, please have a look at current develop, introduced new methods in interface FileSystem.

**Comment by Shuhrat-java** [comment]
I don't see any new method in FileSystem interface?
