### ISSUE TITLE
Getting file size returns negative value ...

### ISSUE THREAD

**Issue by Shuhrat-java** [mjdev/libaums#12]
When some of my files bigger than 2 GB, method calling usbFile.getLength() returns negative value. In the root I saw that you changed long to int format (on getUnsignedInt32(int offset, long value) method). It is the cause of returning negative value for a usb file. Why did you change long value to int?

**Comment by mjdev** [comment]
Thanks, I will have a look at it soon.

**Comment by mjdev** [comment]
Simply changing the return type of getUnsignedInt32 works I assume, right? I pushed to branch feature/http-server, can you test if the problem is resolved for you?

Thanks

**Comment by mjdev** [comment]
Thanks for reporting, I fixed it now ;)

**Comment by Shuhrat-java** [comment]
Yes. Problem solved. 
Thanks.
