### ISSUE TITLE
Video file corrupting when writing in real time... 

### ISSUE THREAD

**Issue by Shuhrat-java** [mjdev/libaums#15]
Hello,
In my project I'm writing real time encoded mp4 video file to USB drive. At the end of recording mp4 file should have some header information. For that ffmpeg seeks for some positions in file and writes some bytes. Some of them are 4 (length of bytes) some of them 40, 64, 233 etc. However in some cases file is being corrupted. I tried to write with same logic to android's sdcard and it is going everytime with success but with USB sometimes fails. Is it related to cluster size or something else? Could you please explain it. I don't know how FAT's behaviour when writing file. Also have a look at http://stackoverflow.com/questions/9108548/android-usb-host-bulktransfer-is-losing-data . Maybe the real cause is android's native bulkTransfer API does not work properly?

**Comment by mjdev** [comment]
Hey,
thanks for reporting, this is definitely a bug, I think seeking to the front and writing there is just not really implemented :/

**Comment by Shuhrat-java** [comment]
However seeking goes backward and forward not only to the front. After seeking bytes will be overwritten on backward

**Comment by mjdev** [comment]
Hey @Shuhrat-java can you please share some more code, in my previous posting I made a mistake, seeking should work fine.
Maybe you can paste the interaction of ffmpeg and libaums.

**Comment by mjdev** [comment]
Closed due to inactivity, if you encounter the error again, please reopen.
