### ISSUE TITLE
UsbFile.createdAt day  is incorrect

### ISSUE THREAD

**Issue by vlog-yamamoto** [mjdev/libaums#16]
UsbFile.createdAt day is from FatDirectoryEntry.decodeDateTime.
FatDirectoryEntry.decodeDateTime day  is following. 
`calendar.set(Calendar.DAY_OF_MONTH, date & 0x0f); `
Day is 0-3 bits

But According to 'table 5.6 Date format, compare to:' from 'https://www.os.in.tum.de/fileadmin/w00bdp/www/Lehre/Abschlussarbeiten/Jahnen-thesis.pdf', Day of month is 0-4 bits.
I change following that I can get correct day. 
`calendar.set(Calendar.DAY_OF_MONTH, date & 0x1f);`

**Comment by mjdev** [comment]
Thanks, can you maybe file a pull request?
