### ISSUE TITLE
NullPointerException when calling root directorys getName() method

### ISSUE THREAD

**Issue by jmue** [mjdev/libaums#19]
When a UsbFile is a root directory it's `entry` class member is `null`. So calling method `getName()` will result in a NullPointerException.

`java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.github.mjdev.libaums.fs.fat32.FatLfnDirectoryEntry.getName()' on a null object reference`

**Comment by mjdev** [comment]
Why would you do this on the root directory?

**Comment by jmue** [comment]
same for method `lastModified()`

**Comment by jmue** [comment]
I'm calling this on Interface `UsbFile`, my logic does not know if this specific element is the root directory.

**Comment by mjdev** [comment]
I see, as a workaround until this is fixed you could check if the directory is the root directory via:
`if(usbFile.getParent() == null) 
    // is root`

**Comment by mjdev** [comment]
Resolved in current develop, please use isRoot() to avoid querying root directory
