### ISSUE TITLE
How to speed up writing time?

### ISSUE THREAD

**Issue by Shuhrat-java** [mjdev/libaums#3]
How can I increase speed of writing file on usb, on which part of code should I look for optimisation?

**Comment by mjdev** [comment]
Hey,

first file you can look at is https://github.com/mjdev/libaums/blob/master/libaums/src/com/github/mjdev/libaums/driver/scsi/ScsiBlockDevice.java

Have a look at the methods read and write.

The optimal solution would be to implement an additional cache layer, which for example reads ahead or does not write immediately, but waits and then writes bigger chunks.

In the filesystem package (FAT32) there is also room for optimization.

**Comment by Shuhrat-java** [comment]
Hey,
Thank you very much. I used caching logic, now I fill buffer with size of 1 MB and then write it to file. Speed dramatically increased ! 
Good luck

**Comment by Shuhrat-java** [comment]
How can I get file creation time?

**Comment by mjdev** [comment]
Currently there is no API für that. Nur I can add that next week. You can also try it via reflections or add the methods yourself and file a pull request.

**Comment by mjdev** [comment]
Please have a look at my latest commit.

**Comment by Shuhrat-java** [comment]
Thank you very much !!!
