### ISSUE TITLE
Doubt: is possible to use to enable the usb mass storage?

### ISSUE THREAD

**Issue by daybson** [mjdev/libaums#31]
I installed the app and I tried to plug a usb pendrive on the smartphone, and the files were listed with success.
But I need to enable/disable the usb mass storage when the user interacts with a button at my activity, to make possible the PC Host read some files on my device. I'm with no luck to find a way to do this without root permission on API 15.
Is possible to use libaums to make this work?
Thanks.

**Comment by mjdev** [comment]
If you are trying to enable the Android mass storage mode, usually done in settings of via notification (if supported), then no sorry, this library does totally different things. Like you already mentioned, it is to use USB flash drives in Android.
