### ISSUE TITLE
java.io.IOException: MAX_RECOVERY_ATTEMPTS

### ISSUE THREAD

**Issue by wangshufu** [mjdev/libaums#387]
Hello, which systems are supported in the current version with read and write functions; I tried the exfat system and found an exception when calling usbMassStorageDevice. init()

java.io.IOException: MAX_RECOVERY_ATTEMPTS Exceeded while trying to transfer command to device, please reattach device and try again

**Comment by auloma04** [comment]
Hello, how did you solve the problem ? I am facing the same but without finiding solutions

**Comment by PratikLahagora** [comment]
@wangshufu @auloma04 Have you found any solution ?

**Comment by PratikLahagora** [comment]
@wangshufu @auloma04 Have you found any solution ?
