### ISSUE TITLE
storageDevices.length is always 0

### ISSUE THREAD

**Issue by androidHRTZ** [mjdev/libaums#395]
Problem
UsbMassStorageDevice.getMassStorageDevices(this) ‘s length is always 0

When 
UsbManager usbManager = (UsbManager) getSystemService(Context.USB_SERVICE);
usbManager.getDeviceList.size() is 1
and 
UsbMassStorageDevice[] storageDevices = UsbMassStorageDevice.getMassStorageDevices(MainActivity.this);
storageDevices.length is always 0

what can i do to solve this problem , thanks .

**Comment by talhacomak** [comment]
Same problem with Canon Camera. When i use a USB Card, there is no problem. When i use Canon Camera as OTG device, the library couldn't see it as Mass Storage Device. However i can reach the files with Android MTP function at notification bar.

**Comment by androidHRTZ** [comment]
> 

Yes，me too，my device is Canon Camera，and  i can get the Canon Camera ‘s images with Android MTP.

**Comment by magnusja** [comment]
MTP is not supported by this library, contributions welcome!
