### ISSUE TITLE
FAT32 partitions size 0

### ISSUE THREAD

**Issue by dgz05011** [mjdev/libaums#397]
FAT32 partitions size 0,i test 3 udisks, 2 of results is 0,just 1 worked in android device

**Comment by zengjie-android** [comment]
I have the same issue, when i call device.getPartitions().get(0), it throws exception, some udisks seems not support FAT32(i am not sure is that reason)

**Comment by magnusja** [comment]
I mean I dont know. With that error description I really cant do anything sorry

**Comment by auloma04** [comment]
Same probleme here. 4 FAT32 devices and no partition is detected on any of these devices:
![image](https://github.com/magnusja/libaums/assets/75633160/c766908b-a650-40a9-858a-b0d86f957106)  
```
  List<Partition> partitions = mUsbMSDevice.getPartitions();
  if(partitions != null) {
    Log.d(TAG, "openDevice: number of partitions " + partitions.size()); // This line prints 0
  } else {
     Log.d(TAG, "openDevice: no partition found");
  }

```
 As we can see the USB key is in MBR:
![image](https://github.com/magnusja/libaums/assets/75633160/c56ab878-6565-4fde-84f5-08416ddc5f76)  
"Disc tag: dos"
