### ISSUE TITLE
getting issue while building CMakeList.txt 

### ISSUE THREAD

**Issue by pavithapichai** [mjdev/libaums#403]
### Problem
When i am trying to run develop branch , getting below issue

#### Stacktrace of Excpetion
[CXX1429] error when building with cmake using C:\Users\pichap3\AndroidStudioProjects\libaums\libusbcommunication\CMakeLists.txt: -- The C compiler identification is Clang 14.0.7
-- The CXX compiler identification is Clang 14.0.7
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Users/pichap3/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Users/pichap3/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done

C++ build system [configure] failed while executing:
    @echo off
    "C:\\Users\\pichap3\\AppData\\Local\\Android\\Sdk\\cmake\\3.22.1\\bin\\cmake.exe" ^
      "-HC:\\Users\\pichap3\\AndroidStudioProjects\\libaums\\libusbcommunication" ^
      "-DCMAKE_SYSTEM_NAME=Android" ^
      "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON" ^
      "-DCMAKE_SYSTEM_VERSION=19" ^
      "-DANDROID_PLATFORM=android-19" ^
      "-DANDROID_ABI=arm64-v8a" ^
      "-DCMAKE_ANDROID_ARCH_ABI=arm64-v8a" ^
      "-DANDROID_NDK=C:\\Users\\pichap3\\AppData\\Local\\Android\\Sdk\\ndk\\25.2.9519653" ^
      "-DCMAKE_ANDROID_NDK=C:\\Users\\pichap3\\AppData\\Local\\Android\\Sdk\\ndk\\25.2.9519653" ^
      "-DCMAKE_TOOLCHAIN_FILE=C:\\Users\\pichap3\\AppData\\Local\\Android\\Sdk\\ndk\\25.2.9519653\\build\\cmake\\android.toolchain.cmake" ^
      "-DCMAKE_MAKE_PROGRAM=C:\\Users\\pichap3\\AppData\\Local\\Android\\Sdk\\cmake\\3.22.1\\bin\\ninja.exe" ^
      "-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\pichap3\\AndroidStudioProjects\\libaums\\libusbcommunication\\build\\intermediates\\cxx\\Debug\\4p2ya139\\obj\\arm64-v8a" ^
      "-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=C:\\Users\\pichap3\\AndroidStudioProjects\\libaums\\libusbcommunication\\build\\intermediates\\cxx\\Debug\\4p2ya139\\obj\\arm64-v8a" ^
      "-DCMAKE_BUILD_TYPE=Debug" ^
      "-BC:\\Users\\pichap3\\AndroidStudioProjects\\libaums\\libusbcommunication\\.cxx\\Debug\\4p2ya139\\arm64-v8a" ^
      -GNinja ^
      "-DLIBUSB_PATH=null"
  from C:\Users\pichap3\AndroidStudioProjects\libaums\libusbcommunication
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

Using libusb path null
CMake Error at CMakeLists.txt:11 (add_library):
  Cannot find source file:

    null/libusb/core.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc

CMake Error at CMakeLists.txt:11 (add_library):
  No SOURCES given to target: libusb

CMake Generate step failed.  Build files cannot be regenerated correctly.
```
(if exists)
```

**Comment by magnusja** [comment]
you need download libusb and configure the path. Have a look in the pipeline file for further refernce
